name: first_flutter_app
description: My first Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  audioplayers: ^0.17.0
  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  flutter_redux: ^0.7.0
  meta: ^1.2.4
  freezed_annotation: ^0.12.0
  redux_epics: ^0.14.0
  rxdart: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  freezed: any
  analyzer: any

flutter:

  uses-material-design: true
  assets:
    - assets/sounds/salut(ro).mp3
    - assets/sounds/salut(en).mp3
    - assets/sounds/ma_numesc(ro).mp3
    - assets/sounds/ma_numesc(en).mp3
    - assets/sounds/cum_esti(ro).mp3
    - assets/sounds/cum_esti(en).mp3
    - assets/sounds/sunt_bine(ro).mp3
    - assets/sounds/sunt_bine(en).mp3
    - assets/sounds/ma_bucur(ro).mp3
    - assets/sounds/ma_bucur(en).mp3

